const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
process.env.NODE_ENV="test";process.env.SESSION_SECRET="test-secret-that-is-safely-long-enough";process.env.SEED_DEMO_DATA="false";
const{createApp}=require("../src/app");const{parseOutput}=require("../src/ai");const{privateIp}=require("../src/fetcher");const{normalizeRss,matchesKeywords}=require("../src/feeds");const H=require("../src/helpers");
test("AI output parser handles labelled and bold formats",()=>{const a=parseOutput("**หัวข้อ:** ข่าว A\nสรุป: s\nเนื้อหา:\nย่อหน้า","x");assert.equal(a.title,"ข่าว A");assert.equal(a.excerpt,"s");assert.equal(a.body,"ย่อหน้า");assert.equal(parseOutput("plain only","fb").title,"fb")});
test("SSRF guard flags private addresses",()=>{for(const ip of ["127.0.0.1","10.1.2.3","192.168.1.1","172.20.0.5","169.254.169.254","::1","fd00::1"])assert.equal(privateIp(ip),true,ip);assert.equal(privateIp("104.21.36.120"),false)});
test("body renderer escapes HTML",()=>{const h=H.renderBody("<script>x</script>\n\n## หัวข้อ\n\n- a");assert.doesNotMatch(h,/<script>/);assert.match(h,/<h2>หัวข้อ<\/h2>/);assert.match(h,/<li>a<\/li>/)});
test("feed normalisation and keyword filter",()=>{const i=normalizeRss({title:"T",link:"https://www.youtube.com/watch?v=dQw4w9WgXcQ",id:"yt:video:dQw4w9WgXcQ",isoDate:"2026-10-01T00:00:00Z"});assert.equal(i.video_id,"dQw4w9WgXcQ");assert.match(i.image_url,/ytimg/);assert.equal(matchesKeywords({title:"Unity 7 released",summary:""},"เกม,unity"),true);assert.equal(matchesKeywords({title:"Phone",summary:""},"เกม"),false)});
test("news pages, seeded sources, admin protection, banner and contact",async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),"tg-news-")),app=createApp({storageDir:dir}),server=app.listen(0,"127.0.0.1");await new Promise(r=>server.once("listening",r));t.after(()=>{server.close();app.locals.db.close();fs.rmSync(dir,{recursive:true,force:true})});const base=`http://127.0.0.1:${server.address().port}`;
 for(const p of ["/news","/videos","/learn","/contact","/jams","/about","/terms","/login","/news/rss.xml"]){const r=await fetch(base+p);assert.equal(r.status,200,p)}
 const home=await (await fetch(base)).text();assert.match(home,/kway-banner/);assert.match(home,/target="_blank"/);assert.match(home,/ดร\.วศิน ภิรมย์/);assert.match(home,/@wasin/);
 for(const p of ["/admin/news","/admin/feed","/admin/sources"]){const r=await fetch(base+p);assert.equal(r.status,403,p)}
 assert.ok(app.locals.db.prepare("SELECT COUNT(*) n FROM news_sources").get().n>=5);
 const db=app.locals.db,tm=new Date().toISOString();db.prepare("INSERT INTO articles(slug,kind,title,excerpt,body,status,created_at,updated_at,published_at) VALUES('n-1','thai_game','ข่าวทดสอบ','สรุป','เนื้อหา **หนา**','published',?,?,?)").run(tm,tm,tm);db.prepare("INSERT INTO articles(slug,kind,title,body,status,created_at,updated_at) VALUES('n-2','thai_game','ยังไม่อนุมัติ','x','pending',?,?)").run(tm,tm);
 const s=await fetch(base+"/news/n-1");assert.equal(s.status,200);assert.match(await s.text(),/<strong>หนา<\/strong>/);assert.equal((await fetch(base+"/news/n-2")).status,404);
 const list=await (await fetch(base+"/news")).text();assert.match(list,/ข่าวทดสอบ/);assert.doesNotMatch(list,/ยังไม่อนุมัติ/);assert.match(await (await fetch(base+"/sitemap.xml")).text(),/\/news\/n-1/)});
test("jam parser (embedded JSON and HTML fallback) and /jams page",async t=>{const{parseJamsHtml,isThai}=require("../src/jams");const d=h=>new Date(Date.now()+h*3600e3).toISOString().slice(0,19).replace("T"," ");
 const a=parseJamsHtml(`{"jams":[{"id":1,"title":"Mini Jam","url":"/jam/mini-jam","start_date":"${d(48)}","end_date":"${d(120)}","joined":5}]}`);assert.equal(a[0].ext_id,"mini-jam");assert.equal(a[0].joined,5);
 const b=parseJamsHtml(`<a href="/jam/one">One</a><div title="${d(5)}"></div><span>lasts 3 days</span><a href="/jam/two">Two</a><i title="${d(50)}"></i><i title="${d(90)}"></i>`);assert.equal(b.length,2);assert.equal(new Date(b[0].end_at)-new Date(b[0].start_at),3*86400000);assert.equal(isThai({title:"Bangkok Jam",host:"",description:""}),true);
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),"tg-jam-")),app=createApp({storageDir:dir}),server=app.listen(0,"127.0.0.1");await new Promise(r=>server.once("listening",r));t.after(()=>{server.close();app.locals.db.close();fs.rmSync(dir,{recursive:true,force:true})});const base=`http://127.0.0.1:${server.address().port}`,tm=new Date().toISOString();
 app.locals.db.prepare("INSERT INTO jams(source,ext_id,title,url,start_at,end_at,is_thai,created_at,updated_at) VALUES('itch','x','Siam Jam Test','https://itch.io/jam/x',?,?,1,?,?)").run(new Date(Date.now()+86400000).toISOString(),new Date(Date.now()+5*86400000).toISOString(),tm,tm);
 const j=await (await fetch(base+"/jams")).text();assert.match(j,/Siam Jam Test/);assert.match(j,/data-countdown=/);const h=await (await fetch(base)).text();assert.match(h,/jam-band/);assert.match(h,/Siam Jam Test/);assert.equal((await fetch(base+"/admin/jams")).status,403)});
