const fs = require("node:fs");
const path = require("node:path");
const bcrypt = require("bcryptjs");
const compression = require("compression");
const express = require("express");
const helmet = require("helmet");
const rateLimit = require("express-rate-limit");
const session = require("express-session");
const multer = require("multer");
const { init, Store } = require("./db");
const { MAX, upload, save, remove } = require("./uploads");
const H = require("./helpers");

function createApp(options={}) {
  const app=express(), root=path.resolve(__dirname,"..");
  const storage=options.storageDir||process.env.STORAGE_DIR||path.join(root,"storage"), uploads=path.join(storage,"uploads");
  fs.mkdirSync(uploads,{recursive:true}); const db=options.db||init(storage);
  const siteUrl=String(process.env.SITE_URL||"https://thaigame.org").replace(/\/+$/,"");
  const secret=process.env.SESSION_SECRET||(process.env.NODE_ENV==="production"?"":H.token(32)); if(!secret)throw new Error("SESSION_SECRET is required");
  app.set("trust proxy",1); app.set("view engine","ejs"); app.set("views",path.join(root,"views")); app.disable("x-powered-by");
  app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],imgSrc:["'self'","data:"],styleSrc:["'self'"],scriptSrc:["'self'"],frameSrc:["https://www.youtube-nocookie.com"],objectSrc:["'none'"],baseUri:["'self'"],formAction:["'self'"]}},crossOriginResourcePolicy:{policy:"same-origin"}}));
  app.use(compression()); app.use(express.static(path.join(root,"public"),{maxAge:"7d"})); app.use("/uploads",express.static(uploads,{maxAge:"30d",immutable:true}));
  app.use(express.urlencoded({extended:true,limit:"1mb"}));
  app.use(session({name:"thaigame.sid",secret,store:new Store(db),resave:false,saveUninitialized:false,rolling:true,cookie:{httpOnly:true,sameSite:"lax",secure:siteUrl.startsWith("https://"),maxAge:1209600000}}));
  app.use((req,res,next)=>{
    if(!req.session.csrf)req.session.csrf=H.token();
    req.user=req.session.uid?db.prepare("SELECT * FROM users WHERE id=? AND status='active'").get(req.session.uid):null;
    if(req.session.uid&&!req.user)delete req.session.uid;
    Object.assign(res.locals,{siteName:"ThaiGame.org",siteUrl,currentUser:req.user,csrfToken:req.session.csrf,currentPath:req.path,categories:H.CATEGORIES,platformOptions:H.PLATFORMS,formatDate:H.date,excerpt:H.excerpt,jsonArray:H.jsonArray,maxUploadMb:MAX,flash:req.session.flash||null});
    delete req.session.flash; next();
  });
  const limiter=rateLimit({windowMs:900000,limit:20,legacyHeaders:false,standardHeaders:"draft-8",message:"ลองเข้าสู่ระบบหลายครั้งเกินไป กรุณารอ 15 นาที"});
  const flash=(req,type,message)=>req.session.flash={type,message};
  const csrf=(req,res,next)=>H.sameToken(req.body?._csrf,req.session.csrf)?next():res.status(403).render("error",{metaTitle:"คำขอหมดอายุ",statusCode:403,message:"กรุณาย้อนกลับและส่งแบบฟอร์มอีกครั้ง"});
  const auth=(req,res,next)=>req.user?next():(flash(req,"info","กรุณาเข้าสู่ระบบก่อน"),res.redirect(`/login?returnTo=${encodeURIComponent(req.originalUrl)}`));
  const admin=(req,res,next)=>req.user?.role==="admin"?next():res.status(403).render("error",{metaTitle:"ไม่มีสิทธิ์",statusCode:403,message:"หน้านี้สำหรับผู้ดูแลระบบ"});
  const can=(u,g)=>Boolean(u&&g&&(u.role==="admin"||Number(u.id)===Number(g.user_id)));
  const returnTo=(v)=>String(v||"").startsWith("/")&&!String(v).startsWith("//")?String(v):"/dashboard";
  const hydrate=(g,relations=false)=>{
    if(!g)return null; const x={...g,platforms:H.jsonArray(g.platforms),categories:H.jsonArray(g.categories)};
    if(relations){x.screenshots=db.prepare("SELECT * FROM screenshots WHERE game_id=? ORDER BY sort_order,id").all(g.id);x.videos=db.prepare("SELECT * FROM videos WHERE game_id=? ORDER BY sort_order,id").all(g.id);x.links=db.prepare("SELECT * FROM game_links WHERE game_id=? ORDER BY sort_order,id").all(g.id);} return x;
  };
  const list=(where="g.status='published'",params=[],limit=60)=>db.prepare(`SELECT g.*,u.display_name owner_name,u.profile_public,u.avatar_path FROM games g JOIN users u ON u.id=g.user_id WHERE ${where} ORDER BY g.featured DESC,g.updated_at DESC LIMIT ?`).all(...params,limit).map(g=>hydrate(g));
  const form=(b={})=>({title_th:H.text(b.title_th,140),title_en:H.text(b.title_en,140),short_description:H.text(b.short_description,220),description:H.text(b.description,12000),developer_name:H.text(b.developer_name,140),release_date:H.text(b.release_date,10),platforms:H.selected(b.platforms,H.PLATFORMS),categories:H.selected(b.categories,Object.keys(H.CATEGORIES)),video_url:H.array(b.video_url).slice(0,3).map(v=>H.text(v,2048)),link_label:H.array(b.link_label).slice(0,8).map(v=>H.text(v,60)),link_url:H.array(b.link_url).slice(0,8).map(v=>H.text(v,2048))});
  const validate=(f,files,old=null)=>{
    const e=[]; if(f.title_th.length<2)e.push("กรุณาใส่ชื่อเกมอย่างน้อย 2 ตัวอักษร"); if(f.short_description.length<20)e.push("คำโปรยควรมีอย่างน้อย 20 ตัวอักษร"); if(f.description.length<50)e.push("รายละเอียดเกมควรมีอย่างน้อย 50 ตัวอักษร"); if(!f.categories.length)e.push("กรุณาเลือกหมวดอย่างน้อย 1 หมวด"); if(!f.platforms.length)e.push("กรุณาเลือกแพลตฟอร์มอย่างน้อย 1 รายการ");
    f.video_url.forEach(v=>{if(v&&!H.youtubeId(v))e.push("พบลิงก์ YouTube ไม่ถูกต้อง");}); f.link_url.forEach((v,i)=>{if(v&&!H.externalUrl(v))e.push(`ลิงก์ภายนอกลำดับที่ ${i+1} ไม่ถูกต้อง`);if(Boolean(v)!==Boolean(f.link_label[i]))e.push(`กรุณาใส่ทั้งชื่อและ URL ของลิงก์ลำดับที่ ${i+1}`);});
    if((old?.screenshots?.length||0)+(files?.screenshots?.length||0)>20)e.push("Screenshot รวมทั้งหมดต้องไม่เกิน 20 ภาพ"); return [...new Set(e)];
  };
  async function media(files,old=""){
    const saved=[];try{let cover=old;if(files?.cover?.[0]){cover=await save(files.cover[0],uploads,"covers",1800,1200);saved.push(cover);}const shots=[];for(const f of files?.screenshots||[]){const p=await save(f,uploads,"screenshots",2200,1600);saved.push(p);shots.push(p);}return{cover,shots,saved,replaced:cover!==old?old:""};}catch(e){saved.forEach(p=>remove(p,uploads));throw e;}
  }
  function relations(id,f,shots=[],offset=0){db.transaction(()=>{db.prepare("DELETE FROM videos WHERE game_id=?").run(id);db.prepare("DELETE FROM game_links WHERE game_id=?").run(id);const v=db.prepare("INSERT INTO videos(game_id,youtube_id,sort_order) VALUES(?,?,?)");f.video_url.map(H.youtubeId).filter(Boolean).forEach((x,i)=>v.run(id,x,i));const l=db.prepare("INSERT INTO game_links(game_id,label,url,sort_order) VALUES(?,?,?,?)");f.link_url.forEach((x,i)=>{const u=H.externalUrl(x);if(u&&f.link_label[i])l.run(id,f.link_label[i],u,i);});const s=db.prepare("INSERT INTO screenshots(game_id,path,sort_order) VALUES(?,?,?)");shots.forEach((p,i)=>s.run(id,p,offset+i));})();}

  app.get("/health",(_q,r)=>{try{db.prepare("SELECT 1").get();r.json({status:"ok"});}catch{r.status(503).json({status:"unavailable"});}});
  app.get("/",(_q,r)=>{const games=list("g.status='published'",[],6),counts={};Object.keys(H.CATEGORIES).forEach(k=>counts[k]=db.prepare("SELECT COUNT(*) n FROM games WHERE status='published' AND categories LIKE ?").get(`%\"${k}\"%`).n);r.render("home",{metaTitle:"รวมผลงานเกมไทย ให้คนทั้งโลกได้ค้นพบ",metaDescription:"ค้นพบเกมจากนักพัฒนาไทย เกมไทยโบราณ และเกมที่ถ่ายทอดศิลปวัฒนธรรมไทย",games,counts,total:db.prepare("SELECT COUNT(*) n FROM games WHERE status='published'").get().n,developers:db.prepare("SELECT COUNT(*) n FROM users WHERE profile_public=1 AND status='active'").get().n});});
  app.get("/games",(req,res)=>{const q=H.text(req.query.q,100),cat=Object.hasOwn(H.CATEGORIES,req.query.category)?req.query.category:"",platform=H.PLATFORMS.includes(req.query.platform)?req.query.platform:"",c=["g.status='published'"],p=[];if(q){c.push("(g.title_th LIKE ? OR g.title_en LIKE ? OR g.short_description LIKE ? OR g.developer_name LIKE ?)");p.push(...Array(4).fill(`%${q}%`));}if(cat){c.push("g.categories LIKE ?");p.push(`%\"${cat}\"%`);}if(platform){c.push("g.platforms LIKE ?");p.push(`%\"${platform}\"%`);}res.render("games/index",{metaTitle:q?`ผลการค้นหา “${q}”`:"ค้นหาเกมไทย",metaDescription:"รวมผลงานเกมไทย",games:list(c.join(" AND "),p),query:q,category:cat,platform});});
  app.get("/games/new",auth,(_q,r)=>r.render("games/form",{metaTitle:"เพิ่มผลงานเกม",mode:"create",game:null,form:form(),errors:[]}));
  app.post("/games/new",auth,upload.fields([{name:"cover",maxCount:1},{name:"screenshots",maxCount:20}]),csrf,async(req,res)=>{
    const f=form(req.body),errors=validate(f,req.files);if(errors.length)return res.status(422).render("games/form",{metaTitle:"เพิ่มผลงานเกม",mode:"create",game:null,form:f,errors});
    const m=await media(req.files);let id;try{const t=new Date().toISOString(),s=H.slug(f.title_en||f.title_th),r=db.prepare(`INSERT INTO games(user_id,slug,title_th,title_en,short_description,description,developer_name,release_date,platforms,categories,cover_path,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(req.user.id,s,f.title_th,f.title_en,f.short_description,f.description,f.developer_name,f.release_date,JSON.stringify(f.platforms),JSON.stringify(f.categories),m.cover,t,t);id=Number(r.lastInsertRowid);relations(id,f,m.shots);flash(req,"success","เผยแพร่ผลงานแล้ว");return res.redirect(`/games/${s}`);}catch(e){m.saved.forEach(p=>remove(p,uploads));if(id)db.prepare("DELETE FROM games WHERE id=?").run(id);throw e;}
  });
  app.get("/games/:slug/edit",auth,(req,res)=>{const g=hydrate(db.prepare("SELECT * FROM games WHERE slug=?").get(req.params.slug),true);if(!g)return res.status(404).render("404",{metaTitle:"ไม่พบเกม"});if(!can(req.user,g))return res.status(403).render("error",{metaTitle:"ไม่มีสิทธิ์",statusCode:403,message:"คุณไม่มีสิทธิ์แก้ไขผลงานนี้"});res.render("games/form",{metaTitle:`แก้ไข ${g.title_th}`,mode:"edit",game:g,form:{...g,video_url:g.videos.map(v=>`https://youtu.be/${v.youtube_id}`),link_label:g.links.map(l=>l.label),link_url:g.links.map(l=>l.url)},errors:[]});});
  app.post("/games/:slug/edit",auth,upload.fields([{name:"cover",maxCount:1},{name:"screenshots",maxCount:20}]),csrf,async(req,res)=>{
    const g=hydrate(db.prepare("SELECT * FROM games WHERE slug=?").get(req.params.slug),true);if(!g)return res.status(404).render("404",{metaTitle:"ไม่พบเกม"});if(!can(req.user,g))return res.status(403).render("error",{metaTitle:"ไม่มีสิทธิ์",statusCode:403,message:"คุณไม่มีสิทธิ์แก้ไข"});
    const f=form(req.body),errors=validate(f,req.files,g);if(errors.length)return res.status(422).render("games/form",{metaTitle:`แก้ไข ${g.title_th}`,mode:"edit",game:g,form:f,errors});
    const m=await media(req.files,g.cover_path);try{db.prepare(`UPDATE games SET title_th=?,title_en=?,short_description=?,description=?,developer_name=?,release_date=?,platforms=?,categories=?,cover_path=?,updated_at=? WHERE id=?`).run(f.title_th,f.title_en,f.short_description,f.description,f.developer_name,f.release_date,JSON.stringify(f.platforms),JSON.stringify(f.categories),m.cover,new Date().toISOString(),g.id);relations(g.id,f,m.shots,g.screenshots.length);if(m.replaced)remove(m.replaced,uploads);flash(req,"success","อัปเดตข้อมูลเกมแล้ว");res.redirect(`/games/${g.slug}`);}catch(e){m.saved.forEach(p=>remove(p,uploads));throw e;}
  });
  app.post("/games/:slug/screenshots/:id/delete",auth,csrf,(req,res)=>{const g=db.prepare("SELECT * FROM games WHERE slug=?").get(req.params.slug);if(!g||!can(req.user,g))return res.status(403).render("error",{metaTitle:"ไม่มีสิทธิ์",statusCode:403,message:"ไม่สามารถลบภาพนี้"});const s=db.prepare("SELECT * FROM screenshots WHERE id=? AND game_id=?").get(req.params.id,g.id);if(s){db.prepare("DELETE FROM screenshots WHERE id=?").run(s.id);remove(s.path,uploads);}res.redirect(`/games/${g.slug}/edit`);});
  app.post("/games/:slug/delete",auth,csrf,(req,res)=>{const g=hydrate(db.prepare("SELECT * FROM games WHERE slug=?").get(req.params.slug),true);if(!g||!can(req.user,g))return res.status(403).render("error",{metaTitle:"ไม่มีสิทธิ์",statusCode:403,message:"ไม่สามารถลบเกมนี้"});db.prepare("DELETE FROM games WHERE id=?").run(g.id);remove(g.cover_path,uploads);g.screenshots.forEach(s=>remove(s.path,uploads));flash(req,"success","ลบผลงานเกมแล้ว");res.redirect(req.user.role==="admin"?"/admin":"/dashboard");});
  app.get("/games/:slug",(req,res)=>{const raw=db.prepare("SELECT g.*,u.display_name owner_name,u.profile_public,u.avatar_path FROM games g JOIN users u ON u.id=g.user_id WHERE g.slug=?").get(req.params.slug);if(!raw||(raw.status!=="published"&&!can(req.user,raw)))return res.status(404).render("404",{metaTitle:"ไม่พบเกม"});db.prepare("UPDATE games SET views=views+1 WHERE id=?").run(raw.id);const game=hydrate({...raw,views:raw.views+1},true),owner=raw.profile_public?db.prepare("SELECT * FROM users WHERE id=? AND status='active'").get(raw.user_id):null;res.render("games/show",{metaTitle:game.title_th,metaDescription:game.short_description,game,owner,canManage:can(req.user,game)});});
  app.get("/developers",(_q,r)=>r.render("developers/index",{metaTitle:"นักพัฒนาเกมไทย",metaDescription:"โปรไฟล์นักพัฒนาและทีมงานเกมไทย",developers:db.prepare("SELECT u.*,COUNT(g.id) game_count FROM users u LEFT JOIN games g ON g.user_id=u.id AND g.status='published' WHERE u.profile_public=1 AND u.status='active' GROUP BY u.id HAVING COUNT(g.id)>0 ORDER BY game_count DESC").all()}));
  app.get("/developers/:id",(req,res)=>{const d=db.prepare("SELECT * FROM users WHERE id=? AND profile_public=1 AND status='active'").get(req.params.id);if(!d)return res.status(404).render("404",{metaTitle:"ไม่พบโปรไฟล์"});res.render("developers/show",{metaTitle:d.display_name,metaDescription:H.excerpt(d.bio,155),developer:d,games:list("g.status='published' AND g.user_id=?",[d.id],100)});});
  app.get("/register",(req,res)=>req.user?res.redirect("/dashboard"):res.render("auth/register",{metaTitle:"สมัครสมาชิก",form:{display_name:"",email:""},errors:[]}));
  app.post("/register",limiter,csrf,(req,res)=>{if(req.user)return res.redirect("/dashboard");const f={display_name:H.text(req.body.display_name,100),email:H.email(req.body.email)},pass=String(req.body.password||""),e=[];if(f.display_name.length<2)e.push("กรุณาใส่ชื่ออย่างน้อย 2 ตัวอักษร");if(!H.validEmail(f.email))e.push("อีเมลไม่ถูกต้อง");if(pass.length<10||pass.length>128)e.push("รหัสผ่านต้องมี 10–128 ตัวอักษร");if(req.body.accept_terms!=="1")e.push("กรุณายอมรับเงื่อนไข");if(db.prepare("SELECT 1 FROM users WHERE email=?").get(f.email))e.push("อีเมลนี้ถูกใช้งานแล้ว");if(e.length)return res.status(422).render("auth/register",{metaTitle:"สมัครสมาชิก",form:f,errors:e});const t=new Date().toISOString(),r=db.prepare("INSERT INTO users(email,password_hash,display_name,accepted_terms_at,created_at,updated_at) VALUES(?,?,?,?,?,?)").run(f.email,bcrypt.hashSync(pass,12),f.display_name,t,t,t);req.session.regenerate(err=>{if(err)throw err;req.session.uid=Number(r.lastInsertRowid);req.session.csrf=H.token();req.session.flash={type:"success",message:"สมัครสมาชิกสำเร็จ"};res.redirect("/dashboard");});});
  app.get("/login",(req,res)=>req.user?res.redirect("/dashboard"):res.render("auth/login",{metaTitle:"เข้าสู่ระบบ",form:{email:""},errors:[],returnTo:returnTo(req.query.returnTo)}));
  app.post("/login",limiter,csrf,(req,res)=>{const f={email:H.email(req.body.email)},u=db.prepare("SELECT * FROM users WHERE email=?").get(f.email),ok=u&&bcrypt.compareSync(String(req.body.password||""),u.password_hash),e=[];if(!ok)e.push("อีเมลหรือรหัสผ่านไม่ถูกต้อง");else if(u.status!=="active")e.push("บัญชีนี้ถูกระงับ");if(e.length)return res.status(401).render("auth/login",{metaTitle:"เข้าสู่ระบบ",form:f,errors:e,returnTo:returnTo(req.body.returnTo)});const go=returnTo(req.body.returnTo);req.session.regenerate(err=>{if(err)throw err;req.session.uid=u.id;req.session.csrf=H.token();req.session.flash={type:"success",message:`ยินดีต้อนรับ ${u.display_name}`};res.redirect(go);});});
  app.post("/logout",auth,csrf,(req,res)=>req.session.destroy(()=>{res.clearCookie("thaigame.sid");res.redirect("/");}));
  app.get("/dashboard",auth,(req,res)=>res.render("dashboard",{metaTitle:"แดชบอร์ดของฉัน",games:db.prepare("SELECT * FROM games WHERE user_id=? ORDER BY updated_at DESC").all(req.user.id).map(g=>hydrate(g))}));
  app.get("/profile/edit",auth,(req,res)=>res.render("profile/edit",{metaTitle:"แก้ไขโปรไฟล์",form:req.user,errors:[]}));
  app.post("/profile/edit",auth,upload.single("avatar"),csrf,async(req,res)=>{
    const f={display_name:H.text(req.body.display_name,100),profile_public:req.body.profile_public==="1"?1:0,bio:H.text(req.body.bio,2000),website_url:H.externalUrl(req.body.website_url),contact_email:H.email(req.body.contact_email),line_id:H.text(req.body.line_id,100),phone:H.text(req.body.phone,50),facebook_url:H.externalUrl(req.body.facebook_url),x_url:H.externalUrl(req.body.x_url),youtube_url:H.externalUrl(req.body.youtube_url),itch_url:H.externalUrl(req.body.itch_url),steam_url:H.externalUrl(req.body.steam_url)},e=[];if(f.display_name.length<2)e.push("ชื่อสั้นเกินไป");if(f.contact_email&&!H.validEmail(f.contact_email))e.push("อีเมลติดต่อไม่ถูกต้อง");const current=String(req.body.current_password||""),next=String(req.body.new_password||"");if(next&&(!bcrypt.compareSync(current,req.user.password_hash)||next.length<10||next.length>128))e.push("ตรวจรหัสผ่านปัจจุบันและรหัสผ่านใหม่อีกครั้ง");if(e.length)return res.status(422).render("profile/edit",{metaTitle:"แก้ไขโปรไฟล์",form:{...req.user,...f},errors:e});
    let avatar=req.user.avatar_path;if(req.file)avatar=await save(req.file,uploads,"avatars",600,600);db.prepare(`UPDATE users SET display_name=?,profile_public=?,bio=?,avatar_path=?,website_url=?,contact_email=?,line_id=?,phone=?,facebook_url=?,x_url=?,youtube_url=?,itch_url=?,steam_url=?,password_hash=?,updated_at=? WHERE id=?`).run(f.display_name,f.profile_public,f.bio,avatar,f.website_url,f.contact_email,f.line_id,f.phone,f.facebook_url,f.x_url,f.youtube_url,f.itch_url,f.steam_url,next?bcrypt.hashSync(next,12):req.user.password_hash,new Date().toISOString(),req.user.id);if(req.file&&req.user.avatar_path)remove(req.user.avatar_path,uploads);flash(req,"success","บันทึกโปรไฟล์แล้ว");res.redirect("/dashboard");
  });
  app.get("/admin",admin,(_q,r)=>r.render("admin",{metaTitle:"ผู้ดูแลระบบ",stats:{games:db.prepare("SELECT COUNT(*) n FROM games").get().n,published:db.prepare("SELECT COUNT(*) n FROM games WHERE status='published'").get().n,users:db.prepare("SELECT COUNT(*) n FROM users").get().n,images:db.prepare("SELECT COUNT(*) n FROM screenshots").get().n},games:db.prepare("SELECT g.*,u.display_name owner_name,u.email owner_email FROM games g JOIN users u ON u.id=g.user_id ORDER BY g.updated_at DESC").all().map(g=>hydrate(g)),users:db.prepare("SELECT u.*,COUNT(g.id) game_count FROM users u LEFT JOIN games g ON g.user_id=u.id GROUP BY u.id ORDER BY u.created_at DESC").all()}));
  app.post("/admin/games/:id/status",admin,csrf,(req,res)=>{const status=req.body.status==="published"?"published":"hidden";db.prepare("UPDATE games SET status=?,admin_note=?,updated_at=? WHERE id=?").run(status,H.text(req.body.admin_note,500),new Date().toISOString(),req.params.id);flash(req,"success","อัปเดตสถานะเกมแล้ว");res.redirect("/admin#games");});
  app.post("/admin/users/:id/status",admin,csrf,(req,res)=>{if(Number(req.params.id)!==Number(req.user.id))db.prepare("UPDATE users SET status=?,updated_at=? WHERE id=?").run(req.body.status==="active"?"active":"suspended",new Date().toISOString(),req.params.id);res.redirect("/admin#users");});
  app.get("/about",(_q,r)=>r.render("about",{metaTitle:"เกี่ยวกับ ThaiGame.org",metaDescription:"พื้นที่ประชาสัมพันธ์และค้นพบเกมไทย"}));
  app.get("/terms",(_q,r)=>r.render("terms",{metaTitle:"เงื่อนไขและนโยบายเนื้อหา"}));
  app.get("/robots.txt",(_q,r)=>r.type("text").send(`User-agent: *\nAllow: /\nDisallow: /dashboard\nDisallow: /admin\nSitemap: ${siteUrl}/sitemap.xml\n`));
  app.get("/sitemap.xml",(_q,r)=>{const paths=["","/games","/developers","/about",...db.prepare("SELECT slug FROM games WHERE status='published'").all().map(g=>`/games/${g.slug}`)];r.type("application/xml").send(`<?xml version="1.0"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${paths.map(p=>`<url><loc>${siteUrl}${p}</loc></url>`).join("")}</urlset>`);});
  app.use((_q,r)=>r.status(404).render("404",{metaTitle:"ไม่พบหน้าที่ต้องการ"}));
  app.use((e,req,res,_n)=>{console.error(e);if(e instanceof multer.MulterError)return res.status(422).render("error",{metaTitle:"อัปโหลดไม่สำเร็จ",statusCode:422,message:e.code==="LIMIT_FILE_SIZE"?`ภาพแต่ละไฟล์ต้องไม่เกิน ${MAX} MB`:"อัปโหลดได้เฉพาะ JPG, PNG หรือ WebP ตามจำนวนที่กำหนด"});res.status(500).render("error",{metaTitle:"ระบบขัดข้อง",statusCode:500,message:process.env.NODE_ENV==="production"?"เกิดข้อผิดพลาด กรุณาลองใหม่":e.message});});
  app.locals.db=db; app.locals.storageDir=storage; return app;
}
module.exports={createApp};
